name = "cloudy"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2023-08-27"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "CLOUDY_D1"
database_name = "cloudy_d1"
database_id = "7a547247-aa17-4ee7-98ae-657464ae89be"

[[r2_buckets]]
binding = "cloudy-demo"
bucket_name = "tinkernerd-cdn"
